title = "Dan Gero's Mountain"
baseURL = "https://brogar2000.xyz"
copyright = "Copyright © 2023 Garrett Brown"

# internationalization
defaultContentLanguage = "en-us"
[languages.en-us]
languageName = "English"
[languages.jp]
languageName = "やまと"
title = "ダン・ゲロの山"

# Syntax highlighting for code blocks
[markup]
  [markup.highlight]
    guessSyntax = true
    lineNos = true
    noClasses = false

[menu]
  [[menu.social]]
  identifier = "mastodon"
  name = "Mastodon (@dangero@vocalounge.cafe)"
  weight =  -80
  url = "https://vocalounge.cafe/@dangero"
  [[menu.social]]
  identifier = "youtube"
  name = "Personal YouTube (@garrettbrown2000)"
  weight = -70
  url = "https://www.youtube.com/@garrettbrown2000"
  [[menu.social]]
  identifier = "youtube-square"
  name = "Music YouTube (@dangero2000)"
  weight = -60
  url = "https://www.youtube.com/@dangeromusic2000"
  
